# Names
STATTRACK = "StatTrak"
BATTLE_SCARRED = "Battle-Scarred"
WELL_WORN = "Well-Worn"
FIELD_TESTED = "Field-Tested"
MIN_WEAR = "Minimal Wear"
FAC_NEW = "Factory New"
MIL_SPEC_GRADE = "Mil-Spec Grade"
RESTRICTED = "Restricted"
CLASSIFIED = "Classified"
COVERT = "Covert"
EXCEEDINGLY_RARE = "Exceedingly Rare"

# Probabilities
CONSUMER_GRADE_PROBABILITY = 0.8
RESTRICTED_PROBABILITY = 0.16
CLASSIFIFIED_PROBABILITY = 0.032
COVERT_PROBABILITY = 0.0064
WELL_WORN_PROBABILITY = 0.0792
BATTLE_SCARRED_PROBABILITY = 0.0993
FIELD_TESTED_PROBABILITY = 0.04318
MIN_WEAR_PROBABILITY = 0.4318
FAC_NEW_PROBABILITY = 0.1471
STAT_TRAK_PROABILITY = 0.1009